version: '3.8'

services:
  web:
    build: .
    container_name: my_web_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d 

volumes:
  db_data:
